### ISSUE TITLE
peerfacilityimport task progress update bug

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#10077]
## Observed behavior

The `progress` and `total_progress` values for the `peerfacilityimport` job are being set and reset inconsistently resulting in the progress percentage coming back as over 1.0 (translating into > 100% values being returned from the api).

`JobProgressMixin.start_progress` is being called from `kolibri.core.auth.management.utils._queueing_tracker_adapter` and thats where I decided I should just write an issue and discuss w/ @rtibbles and/or @bjester 

Logging the values of `self.progress` and `self.total_progress` in `kolibri.core.tasks.job.percentage_progress`, I get the following entries (I believe they're called about 2s apart):

|progress|total progress|
|-|-|
|0|0|
|0|0|
|0|0|
|1|2|
|1|2|
|0|2|
|0|2|
|1|2|
|2|2|
|3|2|
|N|2|

So it starts with 0 on both, then goes straight to 50%, then just counts up infinitely without stopping.

**ALSO** - There isn't a message so the task just says "Unknown" as its status on the loader.

## Expected behavior

- `progress_percent` cannot return anything less than 1.0
- the progress of the job should be updated accurately and reflected accurately via the api

## User-facing consequences

Unclear status of tasks.

## Steps to reproduce

Try to import a facility from another device using the branch at #9896 

## Context

#9896

**Comment by rtibbles** [comment]
A similar issue was fixed here: https://github.com/learningequality/kolibri/pull/9956

**Comment by rtibbles** [comment]
Probable that the issue the above PR resolved, and this issue were caused by this refactor: https://github.com/learningequality/kolibri/pull/9732/commits/e995978a3c8ed483bad684c0504053c2737f492a

**Comment by bjester** [comment]
I approved #9956 but I ran into an issue and realized it wasn't the full fix. I've corrected it in https://github.com/learningequality/kolibri/pull/10075/commits/3349350c4dbc2a1e7f2151baad65e1b38e26cd82 and other changes that were needed in https://github.com/learningequality/kolibri/pull/10075/commits/ac49987594d11a91ef38b4a7ed14969c9660aca6, both contained in https://github.com/learningequality/kolibri/pull/10075

**Comment by rtibbles** [comment]
#10075 has been merged, so hopefully this is now fixed in develop.

**Comment by bjester** [comment]
I think there's still an issue here? I recall seeing % > 100 for syncing

**Comment by thanksameeelian** [comment]
![image](https://user-images.githubusercontent.com/43046460/234084378-a299da7d-5c67-4ff2-8c0e-b84a2c6236f8.png)

**Comment by rtibbles** [comment]
We're making a LOT of progress!

Yes, seems like there's still an issue here, I've definitely also seen this.

**Comment by MisRob** [comment]
I observed this also when changing the facility from the _Profile_ page

![changing-learning-facility](https://github.com/learningequality/kolibri/assets/13509191/520d2967-4a82-4e38-9b36-0296d2e50486)


and in the setup wizard when importing the facility

![Screenshot from 2023-07-11 16-36-55-1](https://github.com/learningequality/kolibri/assets/13509191/ba6ac843-4447-4428-9349-efb93ca9e60f)
