### ISSUE TITLE
After submitting the exam the learner is still allowed to start the exam.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1246]
## Summary
After submitting the exam the learner is still allowed to start the exam. Where as it should show the **Completed** and the learner should not be allowed to retake.

## System information

 - Version: Kolibri 0.4.0aplha2
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login as a learner
2. Start giving an exam.
3. Enter all the answers.
4. Click on submit exam.
5. Ideally the learner should be given completed exam status.

## Screenshots
Before Exam
![before](https://cloud.githubusercontent.com/assets/12776071/25124398/3ab80a34-2449-11e7-993b-ff22a4f9b55c.png)

![mid](https://cloud.githubusercontent.com/assets/12776071/25124508/8b1efee2-2449-11e7-8034-38192fbb99a7.png)

After Exam
![after](https://cloud.githubusercontent.com/assets/12776071/25124403/3c89f778-2449-11e7-9fed-ff93e8712af3.png)

**Comment by rtibbles** [comment]
Interesting, this seems to be a different behaviour to that reported in #1242, what was the difference in work flow that led to this?

**Comment by harishbalachandran** [comment]
@rtibbles Great that you were able to reproduce this. I believe you are not able to reproduce #1242 and I will comment on that bug.

**Comment by rtibbles** [comment]
Should be fixed in latest alpha.

**Comment by yogeshmhaskule** [comment]
@rtibbles Not able to test this because of #1301

**Comment by swapnil106111** [comment]
@rtibbles @aronasorman retested with channel ID you provided (78eed5c0b59b30c0a40c94c17c849af6) but the issue still exists.

![1](https://cloud.githubusercontent.com/assets/12776071/25380872/66fb7d7a-29cf-11e7-9089-a5a6b3eb79b7.png)
![2](https://cloud.githubusercontent.com/assets/12776071/25380873/66fcbb4a-29cf-11e7-841a-2c2648197e99.png)
![3](https://cloud.githubusercontent.com/assets/12776071/25380874/66fe44ce-29cf-11e7-9c31-eb3d6b1aff23.png)

**Comment by indirectlylit** [comment]
I'm still reproducing this. Perhaps related to https://github.com/learningequality/kolibri/issues/1340 ?

**Comment by harishbalachandran** [comment]
I retested in latest alpha 0.4.0aplha5 and this issue is **not** yet fixed.

![exam submit](https://cloud.githubusercontent.com/assets/13453618/25428067/3c7b4c42-2a92-11e7-91e4-99e4b35415b0.png)
![exam start 2](https://cloud.githubusercontent.com/assets/13453618/25428069/3d0bc916-2a92-11e7-9464-a3c7c3528954.png)
![exam start 3](https://cloud.githubusercontent.com/assets/13453618/25428071/40002b08-2a92-11e7-8260-bbe5bc836d23.png)

**Comment by swapnil106111** [comment]
@rtibbles Retested on Kolibri 0.4.0aplha6. Still showing start after submitting the exam but after refreshing showing result.

![screen shot 2017-04-28 at 2 09 12 pm](https://cloud.githubusercontent.com/assets/12776071/25521574/c747a780-2c1d-11e7-949d-c7066c14e38d.png)
![screen shot 2017-04-28 at 2 10 01 pm](https://cloud.githubusercontent.com/assets/12776071/25521588/d75df57a-2c1d-11e7-9cac-c5f9391d3fb3.png)
![screen shot 2017-04-28 at 2 09 12 pm](https://cloud.githubusercontent.com/assets/12776071/25521604/eefac42e-2c1d-11e7-8fba-00deec1b147f.png)

After refreshing:
![screen shot 2017-04-28 at 2 11 16 pm](https://cloud.githubusercontent.com/assets/12776071/25521629/001b6a06-2c1e-11e7-856b-451088d631e1.png)

**Comment by swapnil106111** [comment]
@rtibbles  Tested on Kolibri 0.4.0aplha7. Now, it is working. 

![screen shot 2017-05-02 at 12 30 01 pm](https://cloud.githubusercontent.com/assets/12776071/25607305/73d6ed5e-2f33-11e7-91ae-91d233c1c387.png)
![screen shot 2017-05-02 at 12 30 30 pm](https://cloud.githubusercontent.com/assets/12776071/25607306/73db2ee6-2f33-11e7-9dc9-3c4476d80225.png)
![screen shot 2017-05-02 at 12 30 37 pm](https://cloud.githubusercontent.com/assets/12776071/25607307/73dc38ea-2f33-11e7-8c00-3a255e37bfe1.png)
