### ISSUE TITLE
The answer attempted for a question that requires sorting is incorrect on an exam report. 

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1432]
## Summary

The learner has entered the correct answer while giving the exam for a question that has sorting the answer from least to greatest.
But the coach report has not captured the  correct answer that the learner has inputed, instead it shows the original question.

## System information
 - Version: Kolibri 0.4.0alpha4
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce

1. Create an exam with a question that has sorting (for example from least to greatest to rise versa)
2. Give the correct option. 
3. Check the question attempt and you will observe that the answer is not what you had entered.

## Screenshots
![order](https://cloud.githubusercontent.com/assets/13453618/25663931/ae34578a-3036-11e7-820a-465748723f16.png)

**Comment by rtibbles** [comment]
Edge cases are the best cases.

Seems like the way we are injecting the answer is not working in this instance, I will investigate, but given the range of KA content, I can't be completely confident that we will be able to fix this in every use case.

**Comment by rtibbles** [comment]
I have replicated this, but it seems to be because this is unsupported on this particular widget type in Perseus. The only way to fix this would be an upstream fix to Perseus itself.

**Comment by harishbalachandran** [comment]
@rtibbles When the learner selects and goes to another question and comes back to the same question the recorded answer also changes. There is no way that the learner can get these questions correct.

Enter right answers:
![img-20170518-wa0005](https://cloud.githubusercontent.com/assets/13453618/26193589/5fe50dec-3bd3-11e7-9c42-88a8ac57d184.jpg)

Navigate to some other question:
![img-20170518-wa0003](https://cloud.githubusercontent.com/assets/13453618/26193602/673b5ab0-3bd3-11e7-901f-4b14c4847be1.jpg)

The answer has changed:
![img-20170518-wa0004](https://cloud.githubusercontent.com/assets/13453618/26193631/79a07b86-3bd3-11e7-8e89-4cb28c566212.jpg)

**Comment by rtibbles** [comment]
@harishbalachandran I have found a workaround for this, have implemented it, and it should make it into the release that we send you on 20th May.

**Comment by rtibbles** [comment]
Fixed in https://github.com/learningequality/kolibri-exercise-perseus-plugin/issues/80 - should be in beta5.

**Comment by harishbalachandran** [comment]
@rtibbles Tested in Beta5, Issue persists.

![sort1](https://cloud.githubusercontent.com/assets/13453618/26253981/bb641398-3cd2-11e7-857a-197ce3cf5c3b.png)
![sort2](https://cloud.githubusercontent.com/assets/13453618/26253985/bba8879e-3cd2-11e7-85b8-b34a52ef91cc.png)
![sort3](https://cloud.githubusercontent.com/assets/13453618/26253984/bba81b24-3cd2-11e7-8533-7f97a72e03d1.png)
![sort4](https://cloud.githubusercontent.com/assets/13453618/26253982/bb9ea864-3cd2-11e7-8e1c-0e910b3f266e.png)
![sort5](https://cloud.githubusercontent.com/assets/13453618/26253983/bba6dfd4-3cd2-11e7-9d00-bee75504d40d.png)

**Comment by jamalex** [comment]
@harishbalachandran Note that you'll need to delete your database and start fresh, as the problem involved the saving of the question state, not just the display, so any existing records in your database will still have the issue.

**Comment by harishbalachandran** [comment]
@jamalex deleted entire .Kolibri folder, installed fresh beta5, re-imported the channel , added new learners and then tested today.

**Comment by harishbalachandran** [comment]
@jamalex and @rtibbles seams to work fine, but few other minor issues. Will raise a separate issue for those. 

You can close this.
