### ISSUE TITLE
Few channels does not load the MagoGenie questions where as few other does.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1462]
## Summary

Few channels does not load the MagoGenie questions where as few other does.

Observation:
We have faced this when we are publishing the channel more than once but for the channels that are published only once the questions are loading up.

Following are the channel ID's that does not load MG questions:
`0c68df81a7f74d8988c25bdc401badd0`
`0fca6657d2e14d05981eb67d145dbb73`

Following are the channel ID's that loads MG questions:
`8f64961a91274c35945459f846c9f2cb`

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: Kolibri 0.4.0beta1
 - Operating system: Ubuntu 14.04LTS
 - Browser: Chrome

## How to reproduce

1. Use the channels id's and check the content of MG questions 

## Screenshots

![bullet point in question](https://cloud.githubusercontent.com/assets/13453618/25888933/b1976242-3585-11e7-8916-384927523e4e.png)

![question not loading](https://cloud.githubusercontent.com/assets/13453618/25889116/4eb5aed0-3586-11e7-91e0-6b98f673eced.png)

**Comment by christianmemije** [comment]
Warning I'm seeing:
```
[Vue warn]: Invalid prop: type check failed for prop "itemId". Expected String, got Null. 
(found in component <exercise-perseus-renderer> at...
```

**Comment by rtibbles** [comment]
This is indicative of missing assessmentmetadata in the content database.

**Comment by rtibbles** [comment]
@harishbalachandran this should now be fixed - if you reimport these channels on your current beta, they should be working.

We will be shortly deploying a fix to ensure this never happens again.

**Comment by yogeshmhaskule** [comment]
Reimported channel id -8f64961a91274c35945459f846c9f2cb. Still facing same issue.
