### ISSUE TITLE
Exam report status shows completed where as the learner has not submitted the exam.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1545]
## Summary
Exam status shows completed for in progress exams.

## System information
 - Version: Kolibri 0.4.0beta7
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome
## How to reproduce

1. Give an exam and check the status at the exam reports section 
2. The in progress exam shows completed.

## Screenshots
![completed1](https://cloud.githubusercontent.com/assets/13453618/26310388/3098a10e-3f1e-11e7-8634-a967c24b4574.png)
![q1](https://cloud.githubusercontent.com/assets/13453618/26310406/387027bc-3f1e-11e7-8793-cffad54bb80a.png)
![q2](https://cloud.githubusercontent.com/assets/13453618/26310424/41146900-3f1e-11e7-96dc-afc965af3728.png)
![q6](https://cloud.githubusercontent.com/assets/13453618/26310470/6c4ec91c-3f1e-11e7-9c00-9056ffb4fbdb.png)

This is the only learner who had completed all others status are showing completed which is incorrect. 
![q3](https://cloud.githubusercontent.com/assets/13453618/26310431/48df02e4-3f1e-11e7-878a-3c27294b66be.png)

**Comment by rtibbles** [comment]
Fixed in #1547

**Comment by harishbalachandran** [comment]
@rtibbles The fix has reversed the exam status. Now the learner who has completed is still shown "in progress".
![report1](https://cloud.githubusercontent.com/assets/13453618/26401328/05a1fd20-40a3-11e7-9d8d-678bdce08dfa.png)
![report2](https://cloud.githubusercontent.com/assets/13453618/26401331/065ff744-40a3-11e7-8e1f-9836cdb22431.png)
![reprot1](https://cloud.githubusercontent.com/assets/13453618/26401330/05fc7e6c-40a3-11e7-8c45-f6a280164f80.png)

**Comment by rtibbles** [comment]
D'oh!

**Comment by harishbalachandran** [comment]
This is fixed too @rtibbles @DXCanas 
![whatsapp image 2017-05-25 at 10 56 24 pm](https://cloud.githubusercontent.com/assets/13453618/26462205/73aec7bc-419d-11e7-9840-495211f11521.jpeg)
