### ISSUE TITLE
Delete channel doesn't correspond to same channel name

### ISSUE THREAD

**Issue by laurenlichtman** [learningequality/kolibri#1813]
## Summary

I loaded a few channels into Kolibri and deleted one of the channels (Khan Academy Testing). I then uploaded PhET (completed) and MIT Blossoms (which didn't fully load). I went back to the Manage tab and noticed that Khan Academy Testing is still there. I pressed "Delete" and the pop-up asked me if I was sure I wanted to delete the PhET channel (which I had loaded). I pressed "ok" and PhET was deleted, not Khan Academy Testing. Both Khan Academy Testing and MIT Blossoms (although potentially not complete) are viewable in the Learn tab.

This may be 2-3separate issues but I'm filing only on the delete channel button as this may be the source of the problem. 

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: Kolibri 0.4.0.dev446
 - Operating system: Windows 10
 - Browser: Chrome

## Traceback or relevant snippet from server.log or browser console

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

1. Import multiple channels
2. Delete one of the channels, and notice the name inconsistency.

## Screenshots

![screencapture-127-0-0-1-8080-management-1499702795784](https://user-images.githubusercontent.com/25990164/28027965-fe00f040-6568-11e7-8ef7-81e2b001f8be.png)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

This would be problematic because internet connectivity is limited and if you are choosing to delete a channel, you want to make sure it's the correct one!

**Comment by radinamatic** [comment]
@laurenlichtman Did you use separate browser tabs to import and delete channels? Or were you using one same browser tab for all actions in the Kolibri Management?

**Comment by laurenlichtman** [comment]
I only used one browser tab for all import and deletion.

**Comment by jamalex** [comment]
Unrelated to this issue itself, but worth noting that deleting a channel currently only deletes the channel database, not the underlying content files, so adding the channel back in won't require re-downloading everything.

**Comment by radinamatic** [comment]
That's not ideal if users want to free space on their HD... :thinking: 
When do we plan to implement the full content delete, with all the confirmation workflow in the UI?

**Comment by rtibbles** [comment]
Public release - at the same time as we have selective content sync.

**Comment by indirectlylit** [comment]
> That's not ideal if users want to free space on their HD... :thinking:

agreed - I don't think that'd be the expected behavior

**Comment by jonboiser** [comment]
I'm going to add a patch that will try to address the name inconsistency on the delete modal. There are at least a couple other issues pointed at in the issue, including the fact that KA Testing was not effectively deleted after Lauren's first attempt.

**Comment by laurenlichtman** [comment]
I put this on the dev channel but @jamalex the database file didn't delete for me after deleting from within Kolibri.
![postdeletion](https://user-images.githubusercontent.com/25990164/28032545-d8efb7d6-6578-11e7-830d-5eadfab41327.JPG)

**Comment by jonboiser** [comment]
@jamalex Do you think there might be issues using `os.remove` on Windows?

**Comment by rtibbles** [comment]
Should be mostly fixed in #1814 - not sure about the inconsistency of database deletion though.

**Comment by jonboiser** [comment]
Closing this one and tracking the deletion issue in #1818

**Comment by radinamatic** [comment]
@jonboiser I'm still seeing this on `0.5.0b4` release :confused: 

fresh Win7 VM snapshot, my two small testing channels: 
`8b4d3e6d3d4842ba8ea658335b5dd252` - KhanAcademyTesting
`95a52b386f2c485cb97dd60901674a98` - CK-12 Testing

**Comment by laurenlichtman** [comment]
The same thing has happened for me on the 0.5.0b2 release and the current 0.5.0b4 release. I mentioned this to @jonboiser as I wonder if it has to relate to the underlying issue #1818?

**Comment by rtibbles** [comment]
Does the wrong channel get deleted, or does no channel get deleted? 

If the former, it is this issue, if the latter then it is #1818.

**Comment by radinamatic** [comment]
Actually, both... :joy: 

Wrong channel _appears_ to be deleted, but if you restart the server, it's still there.

**Comment by rtibbles** [comment]
This is now *really* fixed in #1928.
