### ISSUE TITLE
Images of answers are not displayed for questions created through Kolibri Studio

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#2176]
## Summary
We have added the questions into a channel through Kolibri studio and same channels when imported and used does not display the images on the answer section.

Channel used: e7092f51089243aaa8542bf2519bb548

## System information
 - Version: 0.4.5 and 0.5.0
 - Operating system: Ubuntu 14.04LTS
 - Browser: Chrome

## How to reproduce
1. Create a channel.
2. Add a question with images on the answer options.
3. Import the same channel and observe that the images do not render.

## Screenshots
Question on Studio:
![screen shot 2017-09-13 at 6 56 00 pm](https://user-images.githubusercontent.com/13453618/30380456-542ece34-98b7-11e7-8081-7fa4c0ea14c3.png)
Question on Kolbiri:
![image1](https://user-images.githubusercontent.com/13453618/30380493-6c2768e8-98b7-11e7-830d-03f70ce67047.png)
Question on Studio:
![screen shot 2017-09-13 at 6 56 30 pm](https://user-images.githubusercontent.com/13453618/30380692-df83f6d0-98b7-11e7-978e-c4044509f799.png)
Question on Kolbiri:
![image2](https://user-images.githubusercontent.com/13453618/30380672-d6a2b84e-98b7-11e7-80a1-b9e35a30a265.png)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

We want to conduct our baseline exam through Kolibri in our implementation and are unable to do so because of this issue.

**Comment by harishbalachandran** [comment]
@rtibbles @jayoshih, We curated this channel: 9e5305326ed742d0892479dea825a514 15 days back and added questions manually with images in the answer option. We notice that these questions are showing up properly on 0.4.5.

On Kolibri Studio:
![cc image](https://user-images.githubusercontent.com/13453618/30470525-be42af8c-9a12-11e7-9ed2-5946ff85941a.png)

On Kolibri:
![screenshot from 2017-09-15 12_30_17](https://user-images.githubusercontent.com/13453618/30470579-f47083a4-9a12-11e7-8d33-95285bcbf481.png)
![screenshot from 2017-09-15 12_30_24](https://user-images.githubusercontent.com/13453618/30470580-f472551c-9a12-11e7-9420-491fd978669e.png)
![screenshot from 2017-09-15 12_30_34](https://user-images.githubusercontent.com/13453618/30470581-f476b30a-9a12-11e7-9f84-406ad541acb5.png)

**Comment by rtibbles** [comment]
Hi @harishbalachandran - we have replicated, and @jayoshih has made a fix here: https://github.com/fle-internal/content-curation/pull/438

I will let @aronasorman and @jayoshih advise on when the fix is testable, but it will not require a Kolibri upgrade.

**Comment by harishbalachandran** [comment]
Hey @rtibbles This is a wonderful news! Thanks @jayoshih and @aronasorman, will wait for your update.

**Comment by harishbalachandran** [comment]
@aronasorman and @jayoshih, validated yesterday and the issue still persists. Please let us know when this issue will be resolved?

**Comment by jayoshih** [comment]
Hello @harishbalachandran! Could you try reimporting the channel and seeing if it's fixed? We deployed a fix that should handle answers more accurately

**Comment by AntikaChanda** [comment]
Hello @jayoshih! Reimported the channel and validated it but the issue still persists across all grades. Kindly let us know when would this issue be resolved?   

![screenshot from 2017-09-21 12 50 24](https://user-images.githubusercontent.com/30926441/30685858-f708388a-9ed3-11e7-8291-904c4c7f6800.png)

![screenshot from 2017-09-21 13 05 11](https://user-images.githubusercontent.com/30926441/30685723-76637618-9ed3-11e7-833d-f7025869997a.png)

![screenshot from 2017-09-21 13 21 16](https://user-images.githubusercontent.com/30926441/30685788-acd00608-9ed3-11e7-9ae0-773c8c4d7973.png)

![screenshot from 2017-09-21 13 27 08](https://user-images.githubusercontent.com/30926441/30685797-baf2075e-9ed3-11e7-8b58-3efd1843437e.png)

![screenshot from 2017-09-21 13 29 06](https://user-images.githubusercontent.com/30926441/30685808-c52861fa-9ed3-11e7-8304-c4ad9e56f6a9.png)

**Comment by indirectlylit** [comment]
according to @navakk9 this is resolved
