### ISSUE TITLE
Directory /KOLIBRI_DATA no recognized for export on Linux

### ISSUE THREAD

**Issue by nobicycle** [learningequality/kolibri#3274]
### Observed behavior
Export does not recognize KOLIBRI_DATA directory in the root of the system.
The message 'No drives that can be written to are connected to the server' is seen in the browser.
…

### Expected behavior
 KOLIBRI_DATA directory  should be seen for an export.
…

### User-facing consequences

Cannot export, cannot backup data only. Perhaps backup up .kolibri/content is a work around?

…

### Context

Kolibri is run under account kolibri, with home /opt/kolibri

ls / -l|grep KOLIBRI
drwxr-xr-x   2 kolibri kolibri       4096 Feb 28 21:00 KOLIBRI_DATA

[root@barana me]# systemctl status kolibri-pex
● kolibri-pex.service - Kolibri (pex) server
   Loaded: loaded (/usr/lib/systemd/system/kolibri-pex.service; enabled; vendor preset: disabled)
   Active: active (exited) since Wed 2018-02-28 21:01:49 WITA; 2min 46s ago
  Process: 721 ExecStart=/opt/kolibri/bin/kolibri-v0.7.1.pex start (code=exited, status=0/SUCCESS)
 Main PID: 721 (code=exited, status=0/SUCCESS)
    Tasks: 37 (limit: 4915)
   CGroup: /system.slice/kolibri-pex.service
           └─728 /usr/bin/python /opt/kolibri/bin/kolibri-v0.7.1.pex start

Feb 28 21:01:49 barana.net kolibri-pex[721]: INFO     Going to daemon mode, logging to /opt/kolibri/.kolibri/server.log
Feb 28 21:01:49 barana.net kolibri-pex[721]: INFO:kolibri.utils.cli:Going to daemon mode, logging to /opt/kolibri/.kolibri/server.log
Feb 28 21:01:49 barana.net kolibri-pex[721]: 0 static files copied to '/opt/kolibri/.kolibri/static', 406 unmodified.
Feb 28 21:01:49 barana.net kolibri-pex[721]: Operations to perform:
Feb 28 21:01:49 barana.net kolibri-pex[721]:   Apply all migrations: exams, kolibriauth, auth, admin, morango, sessions, logger, content, contenttypes, device
Feb 28 21:01:49 barana.net kolibri-pex[721]: Running migrations:
Feb 28 21:01:49 barana.net kolibri-pex[721]:   No migrations to apply.
Feb 28 21:01:49 barana.net kolibri-pex[721]:   Your models have changes that are not yet reflected in a migration, and so won't be applied.
Feb 28 21:01:49 barana.net kolibri-pex[721]:   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Feb 28 21:01:49 barana.net systemd[1]: Started Kolibri (pex) server.
[root@barana me]# 64M/opt/kolibri/.kolibri/content
bash: 64M/opt/kolibri/.kolibri/content: No such file or directory

[root@barana me]# cat /usr/lib/systemd/system/kolibri-pex.service
[Unit]
Description=Kolibri (pex) server
[Service]
Type=oneshot
RemainAfterExit=yes
PIDFile=/run/kolibri-pex.pid
WorkingDirectory=/opt/kolibri
User=kolibri
SyslogIdentifier=kolibri-pex
ExecStart=/opt/kolibri/bin/kolibri-v0.7.1.pex start
[Install]
WantedBy=multi-user.target

[root@barana me]# grep kolibri /etc/shadow
kolibri:!:17589:0:99999:7:::

**Comment by indirectlylit** [comment]
Hi @nobicycle - I think this might be a duplicate of #3068. Could you confirm?

**Comment by benjaoming** [comment]
@nobicycle the debug information that you posed doesn't contain any real sort of errors? And your systemd service looks like a fine script.

One thing, you wrote this:

```
[root@barana me]# 64M/opt/kolibri/.kolibri/content
bash: 64M/opt/kolibri/.kolibri/content: No such file or directory
```

To  me, that doesn't make any sense. Why would this command exist?

Would also like to ask, if you are aware that you are running `kolibri` with the user account `kolibri`. This means that `~/.kolibri` is relative to where the user's home is. If you want to configure this differently, you can set the `KOLIBRI_HOME` environment.

You can see how to configure environment variables for systemd here: https://coreos.com/os/docs/latest/using-environment-variables-in-systemd-units.html

**Comment by nobicycle** [comment]
@indirectlylit 
Hi,
Not quite. In  #3068 the problem was due to the fact that the mounted volume was not in fstab. In this issue the KOLIBRI_DATA directory is in a fstab mounted volume.

**Comment by nobicycle** [comment]
@benjaoming 
Yes you are right. Kolibri is running perfectly fine except for export.  You are right that "The no such file or directory" does not make sense. I think is must be a hangover from a previous configuration because as I write this:

 find /opt/kolibri ! -user kolibri

returns nothing. And the status is clean:

# systemctl status kolibri-pex

> ● kolibri-pex.service - Kolibri (pex) server
>    Loaded: loaded (/usr/lib/systemd/system/kolibri-pex.service; enabled; vendor preset: disabled)
>    Active: active (exited) since Sun 2018-03-04 21:14:43 WITA; 17min ago
>   Process: 1221 ExecStart=/opt/kolibri/bin/kolibri-v0.7.1.pex start (code=exited, status=0/SUCCESS)
>  Main PID: 1221 (code=exited, status=0/SUCCESS)
>     Tasks: 37 (limit: 4915)
>    CGroup: /system.slice/kolibri-pex.service
>            └─1229 /usr/bin/python /opt/kolibri/bin/kolibri-v0.7.1.pex start
> 
> Mar 04 21:14:43 knowledge.barana.net kolibri-pex[1221]: INFO     Going to daemon mode, logging to /opt/kolibri/.kolibri/server.log
> Mar 04 21:14:43 knowledge.barana.net kolibri-pex[1221]: INFO:kolibri.utils.cli:Going to daemon mode, logging to /opt/kolibri/.kolibri/server.log
> Mar 04 21:14:43 knowledge.barana.net kolibri-pex[1221]: 0 static files copied to '/opt/kolibri/.kolibri/static', 406 unmodified.
> Mar 04 21:14:43 knowledge.barana.net kolibri-pex[1221]: Operations to perform:
> Mar 04 21:14:43 knowledge.barana.net kolibri-pex[1221]:   Apply all migrations: exams, auth, admin, sessions, morango, content, device, kolibriauth, logger, contenttypes
> Mar 04 21:14:43 knowledge.barana.net kolibri-pex[1221]: Running migrations:
> Mar 04 21:14:43 knowledge.barana.net kolibri-pex[1221]:   No migrations to apply.
> Mar 04 21:14:43 knowledge.barana.net kolibri-pex[1221]:   Your models have changes that are not yet reflected in a migration, and so won't be applied.
> Mar 04 21:14:43 knowledge.barana.net kolibri-pex[1221]:   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
> Mar 04 21:14:43 knowledge.barana.net systemd[1]: Started Kolibri (pex) server.
> 

Yes running kolibri under account kolibri. 

Regarding ~/.kolibri I don't think KOLIBRI_HOME needs setting because kolibri is working absolutely fine in all respects, and so it certainly is picking up  ~/.kolibri correctly

**Comment by nobicycle** [comment]
Perhaps I badly explained this issue.
Now running Kolibri 0.9.1 via pip. Systemd service with environment variables are all working fine.
But:

![kolibri-export-where](https://user-images.githubusercontent.com/1372447/39610958-70ec1690-4f86-11e8-90e0-5f5f3082e74f.jpg)

How, on Linux, can I get a directory or a partition or a usb drive recognized for export?

**Comment by lyw07** [comment]
Hi @nobicycle ,

If you can inspect the web page, please then go to `network` section. After that, click the `export` button. You should be able to find a row that calls something like `http://localhost:8080/api/tasks/localdrive/?1526587026929=1526587026929` right after you click the button. What is the result in the `preview` or `response` section inside the `network` section? Thank you!

Example:
<img width="640" alt="screen shot 2018-05-17 at 12 59 52 pm" src="https://user-images.githubusercontent.com/19424916/40200992-9f576c2c-59d2-11e8-9c37-6b547bab2c33.png">

**Comment by nobicycle** [comment]
Update for Kolibri 0.9.2
![450a1079-82e4-4339-8d14-00bc43528906](https://user-images.githubusercontent.com/1372447/40291255-7da1687c-5cf6-11e8-833c-0ddd8446e107.png)
[mounts.txt](https://github.com/learningequality/kolibri/files/2021279/mounts.txt)

Of the mounts shown, I exported successfully to the SYSTEM disk.
But 
sdc      8:32   1     30G  0 disk /run/media/me/36d659da-7460-46d3-ba13-6762fb434733

is a usb disk auto mounted in Thunar file explorer - it is not shown.

**Comment by nobicycle** [comment]
@lyw07 
If I look at network ... is seems to be in a loop ...
![43e4680e-0432-4530-ab07-45ffbb7ccccc](https://user-images.githubusercontent.com/1372447/40291383-481cb6b0-5cf7-11e8-9004-da5660c15664.png)
, rapidly filling up the screen.

Here is a typical record :
http://127.0.0.1:8087/api/tasks/?1526879031536=1526879031536

**Comment by nobicycle** [comment]
Further, I just exported to /home on Linux. A /home/KOLIBRI_DATA directory was created by kolibri  and the exports displayed complete/success. 

But when I now try Import, Kolibri says:

"No drives with Kolibri content are connected to the server"

**Comment by indirectlylit** [comment]
> If I look at network ... is seems to be in a loop ...

Those are expected - it's polling for updates

**Comment by lyw07** [comment]
Hi @nobicycle ,
`/run/media/me/` will not be shown in the current kolibri 0.9.2 because we have /run in our PATH_PREFIX_BLACKLIST. We are going to remove /run in the blacklist in 0.10 so that you will be able to see it in the export drive list when you upgrade to 0.10 (after we release it though).
Regarding `/home/KOLIBRI_DATA`, can you show me the result of `http://127.0.0.1:8087/api/tasks/localdrive` and `ls -l /home/KOLIBRI_DATA`? Thank you!

**Comment by nobicycle** [comment]
http://192.168.1.100:8087/facility/#/classes
This works after logging in as admin

http://127.0.0.1:8087/api/tasks/localdrive/ and
http://192.168.1.100:8087/api/tasks/localdrive/
Generates:
Server Error (500)

ls -l /home/KOLIBRI_DATA
total 4
drwxr-xr-x 4 root root 4096 May 28 15:21 content

$ sudo chown kolibri:kolibri  /home/KOLIBRI_DATA -R
[sudo] password for me: 
[me@tower ~]$ ls -l /home/KOLIBRI_DATA
total 4
drwxr-xr-x 4 kolibri kolibri 4096 May 28 15:21 content

I changed ownership to the kolibri account, but still Export gave "No drives that can be written to are connected to the server"

**Comment by lyw07** [comment]
Hi @nobicycle, does this issue still exist if by any chance, your kolibri has been upgraded to 0.10? Thank you!

**Comment by indirectlylit** [comment]
should be fixed - please notify if not

**Comment by nobicycle** [comment]
Hi, on 0.11 it is not fixed.

"No drives that can be written to are connected to the server"

I have KOLIBRI_DATA directories in the root of the filesystem and on a USB attached drive. Both are owned by user kolibri that runs the service.

> $ ls -l  /KOLIBRI_DATA
> total 4
> drwxr-xr-x 3 kolibri kolibri 4096 Nov 23 00:29 content
> 
> $ ls -l /run/media/me/ACASIS/
> total 7968
> drwxr-xr-x  2 kolibri kolibri    4096 Nov 23 10:28 KOLIBRI_DATA

[server.log.txt](https://github.com/learningequality/kolibri/files/2609563/server.log.txt)
[kolibri.log.txt](https://github.com/learningequality/kolibri/files/2609564/kolibri.log.txt)

**Comment by benjaoming** [comment]
Hi @nobicycle 

Confirming the version from your log: `INFO 2018-11-23 00:09:08,028 cli Version was 0.10.3, new version: 0.11.0`

But did this work at some point or not, I mean have you been able to access the USB in 0.10? If it did work, when did you see the regression the first time and had anything changed on your setup?

This is unfortunate, but so many things can go wrong. So even though one thing might have been fixed, other issues can have occurred.

We made some changes to have the user that runs kolibri by default also be a "desktop" user, meaning a user that has access to USB mount information. Not only the folder where the drive is mounted. I'm not sure exactly what groups or permissions should be set, and it differs between Linux distros. @lyw07 knows perhaps what check you can run.

1) Have you checked that the full path is accessible by the `kolibri` user? I.e. `sudo su -l kolibri -c "ls /run/media/me/ACASIS/"`
2) That the `kolibri` user can access USB devices -- or maybe try to run Kolibri with a desktop user and see if USB devices show up, just for a quick test.

**Comment by lyw07** [comment]
Hi @nobicycle ,

Could you please copy and paste the result of `http://127.0.0.1:8087/api/tasks/tasks/localdrive/` here? Thank you so much!

**Comment by nobicycle** [comment]
@lyw07 
Hi

```
Vary: Accept

[
    {
        "id": "f6e07a292fa67a446194f1d98fff0506",
        "name": "/",
        "path": "/",
        "writable": false,
        "datafolder": "/KOLIBRI_DATA",
        "freespace": 6000893952,
        "totalspace": 41021222912,
        "filesystem": "ext4",
        "drivetype": "",
        "metadata": {
            "channels": []
        }
    },
    {
        "id": "e13dca2cbc7b75841dc59c6bf7294180",
        "name": "/home",
        "path": "/home",
        "writable": false,
        "datafolder": "/home/KOLIBRI_DATA",
        "freespace": 4300378112,
        "totalspace": 75474989056,
        "filesystem": "ext4",
        "drivetype": "",
        "metadata": {
            "channels": []
        }
    },
    {
        "id": "4754663baa38bd66184ca514eefea14d",
        "name": "/mnt/HD02-1T",
        "path": "/mnt/HD02-1T",
        "writable": false,
        "datafolder": "/mnt/HD02-1T/KOLIBRI_DATA",
        "freespace": 141476016128,
        "totalspace": 983433551872,
        "filesystem": "ext4",
        "drivetype": "",
        "metadata": {
            "channels": []
        }
    }
]
```

The server runs under account 'kolibri'
/usr/lib/systemd/system/kolibri.service

```
$ sudo cat /usr/lib/systemd/system/kolibri.service
[Unit]
Description=Kolibri server
[Service]
Type=oneshot
RemainAfterExit=yes
PIDFile=/run/kolibri.pid
WorkingDirectory=/opt/kolibri
User=kolibri
SyslogIdentifier=kolibri
ExecStart=/bin/bash -c "cd /opt/kolibri/kolibri-venv;. /opt/kolibri/kolibri-venv/bin/activate; /opt/kolibri/kolibri-venv/bin/kolibri start"
[Install]
WantedBy=multi-user.target
```

Also note the permissions on a directory I specifically granted access to:

```
$ sudo -u kolibri ls -l    /mnt/HD02-1T/|grep KOL
drwxrwxr-x  2 me kolibri        4096 Dec 14 10:39 KOLIBRI_DATA
```

Access is still         "writable": false, even when I grant full permissions

```
$ sudo -u kolibri ls -l    /mnt/HD02-1T/|grep KOL
drwxrwxr-x  3 kolibri kolibri        4096 Dec 14 10:46 KOLIBRI_DATA
```

**Comment by lyw07** [comment]
Hi @nobicycle,
thank you so much for the information! I will try to figure out what went wrong.

**Comment by rtibbles** [comment]
Fixed in #5226
