### ISSUE TITLE
Lost Channel Listings

### ISSUE THREAD

**Issue by nobicycle** [learningequality/kolibri#3679]
### Description
Channel listings do not persist. Worse, with a big provider like Khan Academy it takes so long to generate the channel listing that Kolibri logs the user out due to inactivity - so the user can never download and generate Khan Academy listings.

Start with a fresh install (pip)
Select some channel in Devices.
Wait for _Generating channel listing. This could take a few minutes…_
Observe the resource tree but do not download anything.
Logout
Restart Kolibri

### Observed behavior
The downloaded channel resource tree is missing.

### Expected behavior
The tree should persist.

### User-facing consequences
Lost time and confusion.

### Steps to reproduce
Start with a fresh install (pip)
Select some channel in Devices.
Wait for _Generating channel listing. This could take a few minutes…_
Observe the resource tree but do not download anything.
Logout
Restart Kolibri

### Context
Browser; Vivaldi and Firefox

Kolibri version | 0.9.1

http://192.168.1.100:8087/

/opt/kolibri/db.sqlite3

Linux-4.14.36-1-MANJARO-x86_64-with-arch-Manjaro-Linux
2 GB

Note this is a similar issue but closed:
https://github.com/learningequality/kolibri/issues/2720

**Comment by rtibbles** [comment]
This is fixed in 0.9.2.

**Comment by indirectlylit** [comment]
@nobicycle [reports](https://github.com/learningequality/kolibri/issues/3696) that this issue persists in 0.9.2:

> #3679 is not fixed on 0.9.2
> I just tested - I had 3 channels with some content.
> I downloaded listings for about 10 other channels.
> Then logged off and restarted Kolibri.
> On returning to Kolibri, I tested 3 of the newly generated channels - all of then started generating listings again.

**Comment by nobicycle** [comment]
Hi, I experienced the same with version 10.1
I was testing the fix of 
https://github.com/learningequality/kolibri/issues/3963
That fix was a success. I was able to download Kahn Academy channel listings.

However,  afterwards I started downloading some content from that channel. After about 8 MB I ran out of internet quota (for the day). Therefore I clicked cancel.

If I then go to Device, I am informed "Content - No channels installed"

Logs attached.
[kolibri.log.txt](https://github.com/learningequality/kolibri/files/2270008/kolibri.log.txt)
[server.log.txt](https://github.com/learningequality/kolibri/files/2270009/server.log.txt)

**Comment by indirectlylit** [comment]
in #4125 @nobicycle reports:

> With Kolibri reporting "No Content", I went ahead to fetch Kahn Academy listings again. Kolibri returned very quickly - I assume it reused the already downloaded listings.

**Comment by lyw07** [comment]
> If I then go to Device, I am informed "Content - No channels installed"

This should be fixed in upcoming 0.10.2 with the PR https://github.com/learningequality/kolibri/pull/4168

**Comment by indirectlylit** [comment]
@nobicycle thanks for your help reporting these. Please let me know if you still reproduce after [upgrading to 0.10.2](https://learningequality.org/download/)
