### ISSUE TITLE
Kolibri doesn't recognize added topic thumbnails on Studio and fails to download upon publishing

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#4948]
### Observed behavior

[Related issue](https://github.com/learningequality/studio/issues/1112) was originally reported on Studio repo, but it turns out to be more on Kolibri side.

As per @rtibbles' words:
> Kolibri doesn't recognize missing thumbnails as the content node being 'incomplete', and therefore does not flag them for download. This is probably because we treat thumbnail files as 'supplementary' so the fact that they are missing is not flagged to the user.

Maybe also related to #3204 or #3821?

### Expected behavior

Ability to download topic thumbnails in Kolibri after they are added on Studio and the channel republished.

### User-facing consequences

Frustration for failing to see added thumbnails. 

### Errors and logs
…

### Steps to reproduce

Add topic thumbs on Studio & publish the channel
Reimport into Kolibri

### Context

…

cc @laurenlichtman @indirectlylit

**Comment by intelliant01** [comment]
Confirmed. All other changes done *independently* except independent thumbnail updates to topic meta-data done are synced into Kolibri upon version update.
When thumbnail change is accompanied with any other change, then the thumbnail sync happens fine upon version update.

**Comment by radinamatic** [comment]
> When thumbnail change is accompanied with any other change, then the thumbnail sync happens fine upon version update

Yes, that is the workaround that can potentially be used, but we should eliminate the need for it.

**Comment by ralphiee22** [comment]
After investigating this issue, should we allow topics to be selected for update within the import selection? This has some UI implications as we currently don't count topics towards the number of resources, so this may lead to some confusion. Or should we automatically download any external files for topics that are already on the device, perhaps when updating the channel metadata? Also, a bit of unexpected behavior.

**Comment by rtibbles** [comment]
The simplest way of explaining this in the UI might be thumbnail updates. And have a single selection to add these (in the case of no other updates). @khangmach @jtamiace thoughts?

**Comment by khangmach** [comment]
@rtibbles what do you mean by a singe selection to add thumbnails?

some of my other thoughts:
- we shouldn't need to flag and say that thumbnails are missing, as it's already self-evident to the user when they see thumbnails on some topics and not on others.
- as a user I would expect the thumbnail download to be automatic, much like any other datatype associated with content coming in via import (content type, content title, license, description etc etc)
- a mechanism to manually add thumbs over in Kolibri seems excessive to me
- perhaps this is a layout issue and can be addressed with the later card UI updates, but IMO having topics missing their thumbnail has been helping scanning of content a TON. It will become incredibly more difficult to differentiate topics from regular content when we mandate thumbs on topics...

**Comment by intelliant01** [comment]
@khangmach I hope you don't mind me jumping in. I think @rtibbles means something as shown in this screenshot -
![firefox_0i4bjesopj](https://user-images.githubusercontent.com/2577060/52537829-d0046400-2d90-11e9-909c-be193a357b97.png)

This seem quite unnecessary as it should be as @ralphiee22 put it -
>  automatically download any external files for topics that are already on the device, perhaps when updating the channel metadata

because as you have put it -

> as a user I would expect the thumbnail download to be automatic, much like any other datatype associated with content coming in via import (content type, content title, license, description etc etc)

even when simply doing a **version update** in the absence of any other change.

Why do you say so? -
> IMO having topics missing their thumbnail has been helping scanning of content a TON. It will become incredibly more difficult to differentiate topics from regular content when we mandate thumbs on topics.

The top left corner has a folder icon to help differentiate topics from regular content i.e. if I got your concern right. And no one is mandating thumbs, it is just that the thumbnails on content and topic nodes do not get updated even when all other meta data (of a topic or content node) does while doing a simple version update on a channel.

**Comment by rtibbles** [comment]
@khangmach I think you may have misunderstood.

I am not suggesting that we allow adding thumbnails within Kolibri. The issue here is that when topic thumbnails have been updated Kolibri does not flag that any new files should be downloaded.

My suggestion therefore, was to expose a single checkbox when there are topic thumbnails to update, that a user can select to force import of these updated thumbnails.

Import of topic thumbnails *is* automatic during content import, but when content has not been updated, the user *cannot* import, so this automatic behaviour cannot happen.

@intelliant01 I do not think that we should update topic thumbnails during channel metadata update, because it could have significant bandwidth implications, and could cause that process to become significantly slower.

It is also worth noting that other supplementary files (such as content thumbnails, and video subtitles) will also be similarly affected by this issue.

**Comment by intelliant01** [comment]
@rtibbles indeed I missed this important implication -
> it could have significant bandwidth implications, and could cause that process to become significantly slower.

Hence, agreed that thumbnail / "supplementary files'" updates (when not accompanied by parent node updates) should be left to the user discretion.

**Comment by khangmach** [comment]
@rtibbles @intelliant01 thanks for clarifying! Makes sense. This updating is surely something we want to encourage so I would think it would be beneficial to have the "update all thumbnails" be checked by default upon page load. 

>The top left corner has a folder icon to help differentiate topics from regular content i.e. if I got your concern right. And no one is mandating thumbs, it is just that the thumbnails on content and topic nodes do not get updated even when all other meta data (of a topic or content node) does while doing a simple version update on a channel.

This is a bigger usability conversation, but the top-left triangle banner doesn't help too much. At a glance all content cards look exactly alike and it's difficult to parse topics from content, which we ultimately want to make an easier task.

**Comment by jtamiace** [comment]
> It is also worth noting that other supplementary files (such as content thumbnails, and video subtitles) will also be similarly affected by this issue.

Here's an example to address >1 kind of supplementary content that Kolibri does not auto-detect in import. I think it should be a separate section from the resources themselves, and all-or-none selection, unless there is a use to selectively importing thumbs & subtitles?

IMO it would be simplest to show this `other content updates` (or other named) section only if there are updates that can be made, and hide those options when there are no supplementary updates

![screen shot 2019-02-11 at 1 07 55 pm](https://user-images.githubusercontent.com/6668144/52593562-1ba12700-2dfe-11e9-83e1-ea9b77978f60.png)

**Comment by khangmach** [comment]
BIG YES^

**Comment by indirectlylit** [comment]
> It is also worth noting that other supplementary files (such as content thumbnails, and video subtitles) will also be similarly affected by this issue.

Shouldn't these changes show up as a content item having an update and therefore being checkable in the existing UI?

**Comment by intelliant01** [comment]
> Shouldn't these changes show up as a content item having an update and therefore being checkable in the existing UI?

Indeed, yes. 

Adding another section IMO, has these UX and implementation downsides -
1. Forcing end user to deal with technical internals.
2. When all these "other contents" are dealt as integral to the core content items then we should not spring a surprise on the users. 
3. The "payload size" of updates chosen should be dynamically updated and shown in the '''Content selected:''' field. 
4. Having a consolidated section for updates overlooks the fact that the end user may be interested in partial updates only. Such an assumption may be okay for small channels but for huge ones like KA it will make a major difference in the download size.

**Comment by indirectlylit** [comment]
possibly related? https://github.com/learningequality/studio/issues/1261

**Comment by rtibbles** [comment]
This should be addressed by the channel upgrade work that is happening for 0.13.0.

**Comment by intelliant01** [comment]
@indirectlylit Issue still persists with 0.13.0 and 0.13.1rc1. Thumbnails are not being synced upon version upgrade. They do so only upon _specific_ content deletion and re-import. Am experiencing this with multiple channels.

![thumbnails_not_updating](https://user-images.githubusercontent.com/2577060/74587359-66f4a380-5017-11ea-9e54-2251192143c7.gif)

**Comment by indirectlylit** [comment]
thanks for the report. I've opened a new issue at https://github.com/learningequality/kolibri/issues/6576 because the thread has grown a bit long
