### ISSUE TITLE
difficult questions are undefined on kolibri-server

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#5225]
### Observed behavior

On coach quiz report at difficult questions tab, when I click the red link label with 1 0f 1 needs help. this message `Sorry! Something went wrong!` was appeared.
* similar to #5133 
![image](https://user-images.githubusercontent.com/38421180/53617878-13c9eb00-3c24-11e9-858e-6bf342dc1ee1.png)

### Errors and logs

…

### Context

Version: 0.12.0b10
OS: Ubuntu-18.04
Installer: kolibri(apt) with kolibri-server Version: 0.2-0beta3
Server: nginx/1.10.3 (Ubuntu)
Browser: Firefox

**Comment by rtibbles** [comment]
Note that this is fixed in 0.12.0b11.

**Comment by radinamatic** [comment]
It was still failing on b11, but fixed on b12 :slightly_smiling_face:
