### ISSUE TITLE
Deleted content shows as 'Already on Device'

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#6573]
### Observed behavior

Deleted content still showing as 'Already on Device'

![unable_to_import](https://user-images.githubusercontent.com/2577060/74585995-e5961480-5008-11ea-9322-8b7c517718c1.gif)

See [this video with subtitles](https://drive.google.com/file/d/1Q4TMfZ0asvxmsfWZJzbCbCbZQRM6lEpM/view?usp=sharing) till 2:40 for quicker understanding.

…

### Expected behavior

Deleted content should not show as 'Already on Device'.

### User-facing consequences

Confusion.

### Errors and logs

Shall share if any needed.

### Steps to reproduce

1. Delete existing content from a channel. Here I am using token `zapok-dofil`.
2. Try to re-import the content.

### Context

Kolibri version: 0.13.1rc1, 0.13.0
OS: Linux / Windows
Content channel: multiple tried.

**Comment by jonboiser** [comment]
Hi @intelliant01, after you delete content, does the deleted content disappear from the Export/Delete page (where you select items that should be installed on the server)? Or are they there still there to export and delete as if they were "already on the device" (and thus consistent from the "Import more..." Page)?

@rtibbles Made a PR #6533 that fixed a similar resource-availability-mismatch after _upgrading_ a channel (and that channel had new items that weren't showing up in the "Import more..." page after the upgrade). The issue with the just-deleted resources being unavailable to re-download deals with a similar area of the code, namely something called `channel_stats`, so it might be related.

**Comment by rtibbles** [comment]
Yeah, we should probably clear the cache on deletion as well.

**Comment by jonboiser** [comment]
Should be fixed by #6626

**Comment by lyw07** [comment]
Hi @intelliant01 ,

We just released `0.13.2 beta1` which includes a fix to your issue. If you are interested in testing out the beta, please feel free to download the Windows installer here: https://drive.google.com/file/d/1IPRB09x-MP43fglHpXImJuKdA5Q9QuDu/view?usp=sharing

For Linux systems, you are able to find the latest beta installers through `kolibri-proposed` PPA: https://launchpad.net/~learningequality/+archive/ubuntu/kolibri-proposed or `PyPI`: https://pypi.org/project/kolibri/0.13.2b1/

Please let us know if you have any questions. Thank you!

**Comment by intelliant01** [comment]
@jonboiser Sorry for the late response. Guess you could reproduce it and got the answer.

> after you delete content, does the deleted content disappear from the Export/Delete page (where you select items that should be installed on the server)? 

Yes.

@lyw07 Updated and tested with 0.13.2-rc3 on Windows. Partially fixed now as is evident in the gif below.

![deleted_content_reimport](https://user-images.githubusercontent.com/2577060/79429040-a6724880-7fe4-11ea-9d47-1ce1d6b4e12e.gif)

Note that I had deleted content for grade 3 prior to upgrading from 0.13.1 to 0.13.2-rc3. Deleted content for grade 4 after the upgrade. And had no choice but to import content for both the grades together. 

Noticed these issues -
i) The deleted content still shows as "Already on device" after clicking on "Import More".  
ii) It is only by working around to click "Select All" checkbox can I reimport the previously deleted content.
iii) The count under resource deletion task and import task seems to consider the topics/folders as well but during selecting contents for deletion or export in the Delete/Export screen it considers content items only.

**Comment by lyw07** [comment]
Thank you @intelliant01 for testing the new installer and providing detailed information about the issue!
I'm going to reopen this issue so we can further investigate it. However, since we are going to release 0.13.2 very soon (this week), we decide to address this issue in another patch release. Please let us know if you have any questions! Thanks!

**Comment by jonboiser** [comment]
This looks to be fixed in the current pre-release 0.14.7a2. This might have had the same root cause #7765, where the wrong cache was being updated as a side-effect of modifying the content library.
