### ISSUE TITLE
Facilities options button popup literally says 'hi'

### ISSUE THREAD

**Issue by kollivier** [learningequality/kolibri#6986]
### Observed behavior

When I click on the facilities options popup, it says "hi" in big letters above the Register and Remove options. It is not clickable.

<img width="916" alt="himarc" src="https://user-images.githubusercontent.com/29585/83688410-36268300-a5a2-11ea-943c-900fb1e23945.png">

Also, looks like maybe the sync all and import facility buttons may be a little too close together?

### Expected behavior

Either remove the "hi" text, or provide a way for me to say hi back. :)

### User-facing consequences

Confusion, fear the dropdown has become sentient.

### Errors and logs

…

### Steps to reproduce

Click on the Options button next to any of the facilities listed in the Facilities tab of the Device section.

### Context

* Kolibri 0.14.0.dev0+git.20200601182600
* Mac OS 10.14
* Kolibri Mac app using latest WebKit / Safari on 10.14, running app from source.

**Comment by kollivier** [comment]
Running latest develop, I no longer see this. Leaving open for someone to check, but possibly has already been fixed!

**Comment by Tlazypanda** [comment]
@kollivier Yeah looks like its not reproducible :sweat_smile: Checked locally but the sync all and import facility buttons problem still lies maybe we can open an issue for it :v: 
![Screenshot from 2020-06-07 01-56-39](https://user-images.githubusercontent.com/33183263/83953926-3fde0e00-a862-11ea-812e-04132ca672cb.png)

**Comment by indirectlylit** [comment]
thanks!

**Comment by indirectlylit** [comment]
> sync all and import facility buttons problem still lies maybe we can open an issue for it

@Tlazypanda would you mind opening an issue?

**Comment by Tlazypanda** [comment]
@indirectlylit Would love to :heart: Have opened it here https://github.com/learningequality/kolibri/issues/7016 Can you check it out and add the relevant tags? Thanks  :v:

**Comment by indirectlylit** [comment]
done, thanks

**Comment by jonboiser** [comment]
The same problem was found running the PEX installer for 0.14b2.

**Comment by nucleogenesis** [comment]
This must have something to do with how the pex is being built and caching of packages - this was fixed 24 days ago in Kolibri Design System here: https://github.com/learningequality/kolibri-design-system/commit/3548f0cb4870da41bc7e466190500d8f3d98e45b

Should be fixed in future builds with: https://github.com/learningequality/kolibri/pull/7039

**Comment by indirectlylit** [comment]
#7039 is merged but I'm still seeing this 🤔 

![image](https://user-images.githubusercontent.com/2367265/85051739-bde8c180-b14c-11ea-9827-661d181ea1b9.png)

**Comment by micahscopes** [comment]
I didn't see this when reviewing #7190.  Does anyone have a concrete idea of what's causing it to persist?

**Comment by indirectlylit** [comment]
This has been addressed! @nucleogenesis figured out that we _must_ bump the version in the design system library's package.json file, or else under many circumstances `yarn` will not upgrade the dependency even if the source location and hash have changed.

Fixed by https://github.com/learningequality/kolibri-design-system/pull/52

![image](https://user-images.githubusercontent.com/2367265/86499447-1ff61900-bd40-11ea-8a4d-b6d62ee18ddb.png)
