### ISSUE TITLE
Setup wizard - Error if Enable passwords on learner accounts is set to 'No'

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8250]
## Observed behavior
I am getting a 500 Server Error after completing the Setup Wizard when the option for 'Enable passwords on learner accounts' is set to 'No'. If the option is left to the default 'Yes' I'm able to finish the Setup Wizard without problems.

## Expected behavior
I should be able to finalize the Setup Wizard without any errors.

## Steps to reproduce the issue
1. Install the following 0.15 alfa 2 build: https://buildkite.com/organizations/learningequality/pipelines/kolibri-windows/builds/1522/jobs/4d506e7c-949f-49ab-9824-32320614996a/artifacts/57eee854-a0f7-4743-baed-0b464a56c21c
2. Select a language in the device setup and click Continue
3. Select the Advanced setup and click Continue
4. Select the New Facility option
5. Enter a name and click Continue
6. Click Continue at 'Enable guest access' and 'Allow anyone to create their own learner account'
7. While at 'Enable passwords on learner accounts' select 'No. Learner accounts can sign in with just a username' and click Continue
8. Fill in the 'Create super admin account' form and click Continue
9. Click Finish at 'Responsibilities as an administrator' - a Something went wrong error will be displayed.

## Additional information

![2021-08-02_12-58-02](https://user-images.githubusercontent.com/79847249/127848823-8d9afba6-86fd-4d5b-a7cd-018b052db3a2.png)

## Errors and logs
Server Error (500)
[logs.zip](https://github.com/learningequality/kolibri/files/6916352/logs.zip)

## Usage Details
 - OS: Windows 10
 - Browser: Chrome

**Comment by pcenov** [comment]
https://learningequality.testquality.com defect [D3](https://learningequality.testquality.com/project/12317/result/2456348/defect/8029).

**Comment by jredrejo** [comment]
Fixed in #8331

**Comment by pcenov** [comment]
Hi @jredrejo I've just retested this using the following [build](https://buildkite.com/learningequality/kolibri-windows/builds/1869) and it's still not fixed - in fact it's exactly as described above. Could you have a look again?

**Comment by jredrejo** [comment]
hi @pcenov  Could you give more details on your server? Probably the problem is due to something unrelated to the password.  Because I'm using that feature everyday without any issue.

**Comment by pcenov** [comment]
Hi @jredrejo this error is observed in both Windows 10 and Ubuntu while going through the setup wizard and selecting Yes to the following options 'Enable guest access/Allow anyone to create their own learner account'. Then at 'Enable passwords on learner accounts' I select No, I fill in the super admin account data and when I click Continue and then Finish I see the error message.
Here are the logs from today: 
[logs.zip](https://github.com/learningequality/kolibri/files/7137936/logs.zip)
