### ISSUE TITLE
browser 'back' does not work for a single class in 'coach'

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8628]
## Observed behavior

When there is a single class, users are automatically redirected to the class upon viewing 'coach'. However, this is currently breaking the 'back' button:

![2021-11-07 18 00 52](https://user-images.githubusercontent.com/2367265/140665461-e2d8972e-5fdf-4811-8d76-fd7ef479dd4d.gif)

## Expected behavior

we should 'replace' the current URL rather than using 'push' to the browser history so that 'back' will correctly work

## User-facing consequences

broken browser history

## Steps to reproduce

* create a single class in a facility
* go to 'facility' app
* click 'coach'
* try to go back to 'facility' using browser back

## Context

0.15.0-beta1

**Comment by sairina** [comment]
I just checked this on `develop`, and, if I'm understanding this correctly, it seems like it's working correctly? I also tried this with deleting that class and creating a brand new class, and it seems like this has been fixed.

![2021-11-23 22 20 28](https://user-images.githubusercontent.com/13563002/143185485-031c0190-82f5-4c64-a7ce-26b90baebfe1.gif)

**Comment by indirectlylit** [comment]
Interesting, I'm still reproducing here on Chrome and FF under mac.

I'm curious - when you look at your browser history from the coach class home page do you see an entry for the _coach_ class list page? Or is the previous page the _facility_ class list?

| nav | browser history from coach class home |
|--|--|
| ![2021-11-24 11 21 26](https://user-images.githubusercontent.com/2367265/143276802-5b22e3a1-96ed-4364-9e95-9c0d3d5a7b13.gif)  | ![image](https://user-images.githubusercontent.com/2367265/143276670-06cbd8c2-0f38-4908-990f-874f1b47f905.png) |

**Comment by indirectlylit** [comment]
I can take a look at this next week if you're not reproducing

**Comment by marcellamaki** [comment]
@indirectlylit if you can take a look at this this week, since @sairina is now out for her conference, that would be great. If not, let me know. I checked in with her earlier and seems like she's still not able to reproduce.

**Comment by indirectlylit** [comment]
updated to use `replace: true` in https://github.com/learningequality/kolibri/pull/8788
