### ISSUE TITLE
Browser's back button behaves differently in setup flow than on-page back button

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#9027]
## Observed behavior

If you use the browser's back button in the setup flow, the experience is different than using the on-page back button which behaves properly.

## Errors and logs

No errors / logs

## Expected behavior

The browser's back button should behave the same as the in-page back button

## User-facing consequences

- A broken setup flow experience and user confusion

## Steps to reproduce

1. Start a fresh instance of Kolibri
2. Continue past the language selection and select `Quick start`
3. Observe you're properly presented with the `Create super admin account` form
3. Go back using browser's back button
4. Select `Advanced setup` instead of `Quick start` and proceed
5. Observe you're incorrectly presented with the `Create super admin account` form again, but should be presented with the facility name form
6. Click browser's back button again
7. Select `Quick start` again and proceed
7. Observe you're incorrectly presented with the `Select a facility setup for this device` form, having never even entered a facility name

## Context

Kolibri 0.15.0
Ubuntu 20.04
Chrome 97.0.4692.71
Perhaps related to https://github.com/learningequality/kolibri/issues/7343

**Comment by marcellamaki** [comment]
Hopefully this will be resolved with the new onboarding flow, so adding there for tracking

**Comment by marcellamaki** [comment]
@pcenov @radinamatic - this is not a new issue, but I think during the course of the new setup wizard work, these concerns should have been resolved. can we do some testing here to ensure that's the case? Then, we can close this out as resolved. Thanks!

**Comment by pcenov** [comment]
@marcellamaki - this issue is still extant in 0.16 and is valid for both 'On my own' and 'Group learning' flows when using the browser's back button.

Video:

https://user-images.githubusercontent.com/79847249/234587198-b5ed2492-8c75-41ed-8c57-fd7ba3514ede.mp4

Screenshot of the error:

![2023-04-26_16-16-59](https://user-images.githubusercontent.com/79847249/234587263-e4ef9bc8-95d8-45d8-901c-f07a0bea3087.png)
