### ISSUE TITLE
Coach>Reports>Quiz score - Incorrect number of attempts

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9444]
## Observed behavior
I see an incorrect number of attempts at 'Coach>Reports>Quiz score' whenever there's a numeric value input as the answer to a quiz question.
For example if the answer is '12' I will see one failed attempt for the first entered digit '1' and one successful attempt for '12'

## Steps to reproduce the issue
1. Install Kolibri 0.15.2
2. Import [Khan Academy's](https://www.khanacademy.org/math/cc-third-grade-math/represent-and-interpret-data/imp-picture-graphs/e/reading_pictographs_2) (English - US curriculum) > Math by grade > 3rd grade > Represent and interpret data > Picture graphs 
3. Create a quiz for 'Read picture graphs (multi-step problems)'
4. Complete the quiz and as a Coach go to Coach>Reports>Quiz score

## Expected result
Correctly displayed number of attempts.

## Screenshots
![2022-05-17_16-32-31](https://user-images.githubusercontent.com/79847249/168823364-c85bf63f-4142-4b3a-8d5d-b85d27c65638.png)

## Usage Details
Ubuntu 20 - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by rtibbles** [comment]
I believe we removed the debounce on the input because it was too long, but seems like we may need something in the 250ms range?

**Comment by rtibbles** [comment]
Fixed in #9723

**Comment by rtibbles** [comment]
Rereported in #12467

**Comment by pcenov** [comment]
@radinamatic - I confirm that this issue is still extant in Kolibri 0.18.1 and can be replicated with any of the exercises in the QA Channel requiring at least a double digit answer:

https://github.com/user-attachments/assets/fb89b08a-25a5-4922-9f79-da65243961ca

**Comment by rtibbles** [comment]
Fixed in #13602
